export const SET_SHOP_CATEGORY = 'SET_SHOP_CATEGORY';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS';
export const REQUEST_PRODUCTS_SUCCESS = 'REQUEST_PRODUCTS_SUCCESS';
export const REQUEST_PRODUCTS_ERROR = 'REQUEST_PRODUCTS_ERROR';
export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';
